<?php

namespace AeroportBundle\Repository;

/**
 * volsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class volsRepository extends \Doctrine\ORM\EntityRepository
{

}
